<?php 
    //
    // skins.php
    //
    // (c) 2000-2002 NextFuture, www.next-future.nl
    //
    // This will handle the editing of skins.
    //

    // we need our library, too
    require "lib.php";

    //
    // RebuildStyleSheet ($id)
    //
    // This will rebuild the style sheet file for skin ID $id.
    //
    function
    RebuildStyleSheet($id) {
	// grab the stylesheet
	$query = sprintf ("SELECT content FROM skin_%s WHERE name='stylesheet'", $id);
	list ($content) = db_fetch_results (db_query ($query));

	// load the variables
	$query = sprintf ("SELECT name,content FROM skinvars_%s", $id);
	$res = db_query ($query);
	while (list ($name, $val) = db_fetch_results ($res)) {
	    $SKIN_VALUE[$name] = $val;
	}

	// fix up the values
	$content = preg_replace ("/\{((\S)*)\}/e", '$SKIN_VALUE["\\1"]', $content);

	// put them into a file
	$fd = @fopen ("../styles/skin" . $id . ".css", "w");
	if (!$fd) {
	    // this failed. complain
 ?>Sorry, but we could not create the style file. This is most likely due to a file permission problem.
<?php
	    cpShowFooter();
	    exit;
	}
	
	// put the data into it
	fputs ($fd, "/* This file is automatically generated, do not edit */\n");
	fputs ($fd, $content);

	// close the file
	fclose ($fd);

	// paranoia (but it can't hurt :)
	@chmod ("../styles/skin" . $id . ".css", 0644);
    }

    //
    // Overview()
    //
    // This will take care the skin overview
    //
    function
    Overview() {
	// build the query
	$query = sprintf ("SELECT name,description,flags,id FROM skins");
	$res = db_query ($query);

	// build the layout
	cpShowHeader("Skin Maintenance", "Overview");
 ?><table width="100%" cellspacing="2" cellpadding="3" border="0" class="tab1">
<tr>
  <td class="tab3" width="100%" colspan=2><b>Skin name</b></td>
</tr>
<?php
	// add all skins
	while (list ($name, $desc, $flags, $id) = db_fetch_results ($res)) {
	    $extra = ""; $inuse = "";
	    if (($flags & FLAG_SKIN_DEFAULT) != 0) {
		// this the default skin. modify the table attribute
		$setdef = "(<b>default skin</b>)";
	    } else {
		$setdef = sprintf ("(<a href=\"%s?action=setskindefault&id=%s\">set as default</a>)", $_SERVER["PHP_SELF"], $id);
	    }

	    printf ("<tr class=\"tab2\"><td width=\"80%%\"><a href=\"%s?action=editskin&id=%s\">%s</a></td><td width=\"20%%\" align=\"right\">$setdef</td></tr>", $_SERVER["PHP_SELF"], $id, $name);
	}
?></table>
<form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="hidden" name="action" value="importskin">
<input type="submit" value="Import skin">
</form>
<?php
	cpShowFooter();
    }
    
    //
    // EditSkin()
    //
    // This will show the page for skin editing.
    //
    function
    EditSkin() {
	// sow the header
	cpShowHeader("Skin Maintenance", "Edit skin");

	// fetch the skin id
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);

	// grab the name of the skin
	$query = sprintf ("SELECT name FROM skins WHERE id='%s'", $id);
	list ($skinname) = db_fetch_results (db_query ($query));

	// grab all skin information for the database
	$query = sprintf ("SELECT name,description FROM skin_%s ORDER BY name", $id);
	$res = db_query ($query); $nofmatches = db_nof_results ($res);

	// show how much hits we have
	print "This skin, <b>$skinname</b>, has <b>$nofmatches</b> template";
	if ($nofmatches != 1) { echo "s"; };
 ?><p><table width="100%" cellspacing="2" cellpadding="3" border="0" class="tab1">
 <tr>
  <td width="25%" class="tab3">Template Name</td>
  <td width="75%" class="tab3">Description</td>
 </tr>
<?php
	
	// show them all
	while (list ($name, $desc) = db_fetch_results ($res)) {
	    printf ("<tr class=\"tab2\"><td><a href=\"%s?action=editskintemplate&id=%s&template=%s\">%s</a></td><td class=\"text\">%s</td></tr>", $_SERVER["PHP_SELF"], $id, rawurlencode ($name), $name, $desc);
	}
 ?></table><p><table width="100%">
 <tr>
  <td width="25%" align="center">
    <form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
    <input type="hidden" name="action" value="addskintemplate">
    <input type="hidden" name="id" value="<?php echo $id; ?>">
    <input type="submit" value="Add template">
    </form>
  </td>
  <td width="25%" align="center">
    <form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
    <input type="hidden" name="action" value="editskinvars">
    <input type="hidden" name="id" value="<?php echo $id; ?>">
    <input type="submit" value="Edit skin variables">
    </form>
  </td>
  <td width="25%" align="center">
    <form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
    <input type="hidden" name="action" value="deleteskin">
    <input type="hidden" name="id" value="<?php echo $id; ?>">
    <input type="submit" value="Delete skin">
    </form>
  </td>
  <td width="25%" align="center">
    <form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
    <input type="hidden" name="action" value="exportskin">
    <input type="hidden" name="id" value="<?php echo $id; ?>">
    <input type="submit" value="Export skin">
    </form>
  </td>
 </tr>
</table>
<?php
	cpShowFooter();
    }

    //
    // EditSkinTemplate()
    //
    // This will edit a skin template for us.
    //
    function
    EditSkinTemplate() {
	// show the header
	cpShowHeader("Skin Maintenance", "Edit skin template");

	// grab the values
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);
	$template = $_REQUEST["template"];

	// grab the contents from the database
	$query = sprintf ("SELECT content,title,refresh_url,description FROM skin_%s WHERE name='%s'", $id, $template);
	list ($content, $title, $refreshurl, $desc) = db_fetch_results (db_query ($query));

	// build the layout
 ?><form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="hidden" name="action" value="doeditskintemplate">
<input type="hidden" name="id" value="<?php echo $id; ?>">
<input type="hidden" name="template" value="<?php echo $template; ?>">
<table width="100%" class="tab5" cellspacing="1" cellpadding="4" border="0">
<tr class="tab2">
  <td width="20%"><b>Template name</b></td>
  <td width="80%"><input type="text" name="the_template" value="<?php echo $template; ?>"></td>
</tr>
<tr class="tab2">
  <td><b>Page Title</b></td>
  <td><input type="text" name="the_title" value="<?php echo htmlspecialchars ($title); ?>"></td>
</tr>
<tr class="tab2">
  <td><b>Refresh URL</b></td>
  <td><input type="text" name="the_refreshurl" value="<?php echo htmlspecialchars ($refreshurl); ?>"></td>
<tr class="tab2">
  <td><b>Description</b></td>
  <td><input type="text" name="the_desc" value="<?php echo htmlspecialchars ($desc); ?>"></td>
</tr>
<tr class="tab2">
  <td valign="top"><b>Content</b></td>
  <td><textarea name="the_content" rows=20 cols=55><?php echo htmlspecialchars ($content); ?></textarea></td>
</tr></table><p>
<table width="100%">
 <tr valign="top">
  <td width="50%" align="center"><input type="submit" value="Commit Changes"></form></td>
  <td width="50%" align="center"><form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post"><input type="hidden" name="action" value="deleteskintemplate"><input type="hidden" name="id" value="<?php echo $id; ?>"><input type="hidden" name="template" value="<?php echo $template; ?>"><input type="submit" value="Delete Skin Template"></td>
 </tr>
</table>
<?php
	cpShowFooter();
    }

    //
    // DoEditSkinTemplate()
    //
    // This will actually modify the skin template.
    //
    function
    DoEditSkinTemplate() {
	// show the header
	cpShowHeader("Skin Maintenance", "Edit skin template");

	// fetch the values
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);
	$template = $_REQUEST["template"];
	$the_template = $_REQUEST["the_template"];
	$the_content = $_REQUEST["the_content"];
	$content = $_REQUEST["the_content"];
	$the_title = $_REQUEST["the_title"];
	$the_refreshurl = $_REQUEST["the_refreshurl"];
	$the_desc = $_REQUEST["the_desc"];

	// modify it
	$query = sprintf ("UPDATE skin_%s SET name='%s',content='%s',title='%s',refresh_url='%s',description='%s' WHERE name='%s'", $id, $the_template, $the_content, $the_title, $the_refreshurl, $the_desc, $template);
        db_query ($query);

	// was this the special 'stylesheet' template?
	if ($the_template == "stylesheet") {
	    // yes. rebuild it
	    RebuildStyleSheet ($id);
	}

 ?>Thank you, the template has successfully been updated.<p>
<form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="hidden" name="action" value="editskin">
<input type="hidden" name="id" value="<?php echo $id; ?>">
<input type="submit" value="Return to skin editing">
</form>
<?php
	cpShowFooter();
    }

    //
    // AddSkinTemplate()
    //
    // This will add the skin template.
    //
    function
    AddSkinTemplate() {
	// build the page
	cpShowHeader("Skin Maintenance", "Add skin template");
 ?><form action="<?php echo $PHP_SELF; ?>" method="post">
<input type="hidden" name="action" value="doaddskintemplate">
<input type="hidden" name="id" value="<?php echo preg_replace ("/\D/", "", $_REQUEST["id"]); ?>">
<table width="100%" class="tab5" cellspacing="1" cellpadding="4" border="0">
<tr class="tab2">
  <td width="20%"><b>Template name</b></td>
  <td width="80%"><input type="text" name="the_template"></td>
</tr>
<tr class="tab2">
  <td><b>Page Title</b></td>
  <td><input type="text" name="the_title"></td>
</tr>
<tr class="tab2">
  <td><b>Refresh URL</b></td>
  <td><input type="text" name="the_refreshurl"></td>
</tr>
<tr class="tab2">
  <td><b>Description</b></td>
  <td><input type="text" name="the_desc"></td>
</tr>
<tr class="tab2">
  <td valign="top"><b>Content</b></td>
  <td><textarea name="the_content" rows=15 cols=50></textarea></td>
</tr></table><p>
<center><input type="submit" value="Add template"></center>
</form>
<?php
	cpShowFooter();
    }

    //
    // DoAddSkinTemplate()
    //
    // This will actually add a skin template.
    //
    function
    DoAddSkinTemplate() {
	global $id, $the_template, $the_content, $the_refreshurl;
	global $the_title, $PHP_SELF, $the_desc;

	// fetch the values
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);
	$the_template = $_REQUEST["the_template"];
	$the_content = $_REQUEST["the_content"];
	$the_title = $_REQUEST["the_title"];
	$the_refreshurl = $_REQUEST["the_refreshurl"];
	$the_desc = $_REQUEST["the_desc"];

	// build the query
	$query = sprintf ("INSERT INTO skin_%s VALUES ('%s','%s','%s','%s','%s')", $id, $the_template, $the_content, $the_title, $the_refreshurl, $the_desc);
	db_query ($query);

	// show the 'yay' page
	cpShowHeader("Skin Maintenance", "Add skin template");
 ?>Thank you, the template has successfully been added.<p>
<form action="<?php echo $PHP_SELF; ?>" method="post">
<input type="hidden" name="action" value="editskin">
<input type="hidden" name="id" value="<?php echo $id; ?>">
<input type="submit" value="Return to skin editing">
</form>
<?php
	cpShowFooter();
    }

    //
    // QuoteString ($str)
    //
    // This will quote ", ' and $ in $str.
    //
    function
    QuoteString ($str) {
	$str = str_replace ("$", "\\$", $str);
	$str = str_replace ("\"", "\\\"", $str);
	$str = str_replace ("\'", "\\\'", $str);
	return $str;
    }

    //
    // ExportSkin()
    //
    // This will export the skin.
    //
    function
    ExportSkin() {
	// fetch the skin id
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);

	// get the skin name
	$query = sprintf ("SELECT name FROM skins WHERE id='%s'", $id);
	list ($skinname) = db_fetch_results (db_query ($query));

	// build the query
	$query = sprintf ("SELECT name,content,title,refresh_url,description FROM skin_%s", $id);
	$res = db_query ($query);

	// add all fields
	$export = "";
	while (list ($name, $content, $title, $refresh, $desc) = db_fetch_results ($res)) {
	    // add it to the skin
	    $content = str_replace ("\\1", "\\[1]", $content);
	    $content = str_replace ("\\2", "\\[2]", $content);
	    $content = str_replace ("\r", "", $content);
	    $content = str_replace ("\n", "\\n", $content);

	    $export .= "\$SKIN[\"" . QuoteString ($name) . "\"]=\"" . QuoteString ($content) . "\";\n";
	    $export .= "\$SKINTITLE[\"" . QuoteString ($name) . "\"]=\"" . QuoteString ($title) . "\";\n";
	    $export .= "\$SKINREFRESH[\"" . QuoteString ($name) . "\"]=\"" . QuoteString ($refresh) . "\";\n";
	    $export .= "\$SKINDESC[\"" . QuoteString ($name) . "\"]=\"" . QuoteString ($desc) . "\";\n";
	}

	// add the skin variables
	$query = sprintf ("SELECT name,content,description FROM skinvars_%s", $id);
	$res = db_query ($query);

	// add all fields
	while (list ($name, $content, $desc) = db_fetch_results ($res)) {
	    // add it to the skin
	    $content = addslashes ($content);
	    $content = preg_replace ("/\r/", "", $content);
	    $content = preg_replace ("/\n/", "\\n", $content);

	    $export .= "\$SKINVAR[\"" . $name . "\"]=\"" . $content . "\";\n";
	    $export .= "\$SKINVAR_DESC[\"" . $name . "\"]=\"" . $desc . "\";\n";
	}

	// add the final check
	$export .= "\$SKINVERSION = \"" . FORUMAX_VERSION . "\";";

	// send the appropriate headers
	Header ("Content-Type: text/unknown");
	Header ("Content-Disposition: filename=\"" . $skinname . ".txt\"");
	Header ("Content-Transfer-Encoding: ascii");

	// send the content
	echo $export;
    }

    //
    // ImportSkin()
    //
    // This will show the page for importing skins
    //
    function
    ImportSkin() {
	// display the page
	cpShowHeader("Skin Maintenance", "Import skin");
 ?><form enctype="multipart/form-data" action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="hidden" name="action" value="doimportskin">
<input type="hidden" name="MAX_FILE_SIZE" value="1048576">
<table width="100%" class="tab5" cellspacing="1" cellpadding="4" border="0">
 <tr class="tab3">
  <td colspan=2 align="center">Import Skin</td>
 </tr>
 <tr class="tab2">
  <td width="20%">Skin name</td>
  <td width="80%"><input type="text" name="skinname"></td>
 </tr>
 <tr class="tab2">
  <td>Skin description</td>
  <td><input type="text" name="skindesc"></td>
 </tr>
 <tr class="tab2">
  <td>Skin source</td>
  <td><input type="file" name="skinsource"></td>
 </tr>
</table><p>
<center><input type="submit" value="Import this skin"></center>
</form>
<?php

	cpShowFooter();
    }

    //
    // DoImportSkin()
    //
    // This will actually import the forum skin.
    //
    function
    DoImportSkin() {
	global $skinname, $skindesc, $skinsource, $PHP_SELF;

	// show the header
	cpShowHeader("Skin Maintenance", "Import skin");

	// is the file correctly uploaded?
	if (!is_uploaded_file ($_FILES["skinsource"]["tmp_name"])) {
	    // no. complain
 ?>You did not supply a skin source file. You must supply a skin file which contains the exported skin information.
<?php
	    cpShowFooter();
	    exit;
	}

	// read the skin file
	$fd = @fopen ($_FILES["skinsource"]["tmp_name"], "rt");
	if (!$fd) {
 ?>We could not open the skin file. This may be a problem with your web server, please consult your system administrator.
<?php
	    cpShowFooter();
	    exit;
	}

	// read everything
	$skindata = "";
	while (!feof ($fd)) {
	    $skindata .= fread ($fd, 65536);
	}

	// close the file
	fclose ($fd);

	// evaluate the skin
	eval ($skindata);

	// okay, do we have a skin version now?
	if ($SKINVERSION == "") {
	    // no. complain
 ?>This does not appear to be a valid ForuMAX skin file.
<?php
	    cpShowFooter();
	    exit;
	}

	// is the version correct?
	if ($SKINVERSION != FORUMAX_VERSION) {
	    // no. complain
 ?>We're sorry, but this skin is designed for <b>ForuMAX <?php echo $SKINVERSION; ?></b>, which is not the same as your <b>ForuMAX <?php echo FORUMAX_VERSION; ?></b>.
<?php
	    cpShowFooter();
	    exit;
	}

	// add the skin to the list of available skins
	$query = sprintf ("INSERT INTO skins VALUES (NULL,'%s','%s',0)", $skinname, $skindesc);
	$res = db_query ($query);
	$id = db_get_insert_id ($res);

	// build the skin database
	$query = sprintf ("CREATE TABLE skin_%s (name VARCHAR(64) NOT NULL PRIMARY KEY,content TEXT NOT NULL,title VARCHAR(64) NOT NULL,refresh_url VARCHAR(64) NOT NULL,description VARCHAR(128) NOT NULL)", $id);
	db_query ($query);

	// browse all templates
	$tmp = "";
	while (list ($name, $content) = each ($SKIN)) {
	    // feed them into the database
	    $name = addslashes ($name); $content = addslashes ($content);
	    $refresh = addslashes ($SKINREFRESH[$name]);
	    $title = addslashes ($SKINTITLE[$name]);
	    $desc = addslashes ($SKINDESC[$name]);

	    // fix up the content
	    $content = str_replace ("\\[1]", "\\\\1", $content);
	    $content = str_replace ("\\[2]", "\\\\2", $content);

	    // insert them into the database
	    $query = sprintf ("INSERT INTO skin_%s VALUES ('%s','%s','%s','%s','%s')", $id, $name, $content, $title, $refresh, $desc);
	    db_query ($query);
	}

	// also add the variables
	$query = sprintf ("CREATE TABLE skinvars_%s (name VARCHAR(64) NOT NULL PRIMARY KEY,content VARCHAR(128) NOT NULL,description VARCHAR(128) NOT NULL)", $id);
	db_query ($query);

	// browse all variables
	while (list ($name, $content) = each ($SKINVAR)) {
	    // grab the description, too
	    $desc = $SKINVAR_DESC[$name];

	    // feed them into the database
	    $query = sprintf ("INSERT INTO skinvars_%s VALUES ('%s','%s','%s')", $id, $name, $content, $desc);
	    db_query ($query);
	}

	// build the skin's stylesheet
	RebuildStyleSheet ($id);

	// yay, it worked. inform the user
 ?>The skin has successfully been imported.<p>
<form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="submit" value="Return to skin overview">
</form>
<?php
	cpShowFooter();
    }

    //
    // DeleteSkin()
    //
    // This will delete a skin.
    //
    function
    DeleteSkin() {
	// show the header
	cpShowHeader("Skin Maintenance", "Delete skin");

	// fetch the skin id
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);

	// is this the default skin?
	$query = sprintf ("SELECT id FROM skins WHERE (flags&%s)!=0", FLAG_SKIN_DEFAULT);
	$res = db_query ($query); list ($defid) = db_fetch_results ($res);
	if ($defid == $id) {
	    // yes. refuse to delete it
 ?>Sorry, but you cannot delete the default skin<p>
<form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="submit" value="Return to skin overview">
</form><?php
	    cpShowFooter();
	    exit;
	}

	// build the query
	$query = sprintf("DELETE FROM skins WHERE id='%s'", $id);
	db_query ($query);

	// kill the skin table
	$query = sprintf ("DROP TABLE skin_%s", $id);
	db_query ($query);

	// kill the skin variable table
	$query = sprintf ("DROP TABLE skinvars_%s", $id);
	db_query ($query);

	// zap the stylesheet too
	@unlink ("../styles/skin" . $id . ".css");

	// it worked. show the 'yay' page
 ?>The skin has successfully been deleted.<p>
<form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="submit" value="Return to skin overview">
</form>
<?php
	cpShowFooter();
    }

    //
    // SetSkinDefault()
    //
    // This will set a skin as the default skin.
    //
    function
    SetSkinDefault () {
	// show the header
	cpShowHeader("Skin Maintenance", "Set default skin");

	// fetch the skin id
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);

	// flag the current default skin as no longer default
	$query = sprintf ("UPDATE skins SET flags = flags AND NOT %s", FLAG_SKIN_DEFAULT);
	db_query ($query);

	// activate the new default skin
	$query = sprintf ("UPDATE skins SET flags = flags OR %s WHERE id='%s'", FLAG_SKIN_DEFAULT, $id);
	db_query ($query);

	// show the 'yay' page
	print "Thank you, the skin has successfully been activated as default skin";
 ?><form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="submit" value="Return to skin management">
</form>
<?php
	cpShowFooter();
    }

    //
    // EditSkinVars()
    //
    // This will list the available skin variables available for editing.
    //
    function
    EditSkinVars() {
	// show the header
	cpShowHeader("Skin Maintenance", "Edit Skin Variables");

	// fetch the skin id
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);

	// grab all skin information for the database
	$query = sprintf ("SELECT name,description FROM skinvars_%s", $id);
	$res = db_query ($query); $nofmatches = db_nof_results ($res);

	// show how much hits we have
	print "This skin has <b>$nofmatches</b> variable";
	if ($nofmatches != 1) { echo "s"; };

 ?><p><table width="100%" cellspacing="2" cellpadding="3" border="0" class="tab1">
 <tr>
  <td width="25%" class="tab3">Variable Name</td>
  <td width="75%" class="tab3">Description</td>
 </tr>
<?php
	// show them all
	while (list ($name, $desc) = mysql_fetch_row ($res)) {
	    printf ("<tr class=\"tab2\"><td><a href=\"$PHP_SELF?action=editskinvar&id=%s&destvar=%s\">%s</a></td><td>%s</td></tr>", $id, rawurlencode ($name), $name, $desc);
	}
 ?></table><p>
<table width="100%">
 <tr>
  <td width="50%" align="center">
   <form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
   <input type="hidden" name="action" value="addskinvar">
   <input type="hidden" name="id" value="<?php echo $id; ?>">
   <input type="submit" value="Add skin variable">
   </form>
  </td>
  <td width="50%" align="center">
   <form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
   <input type="hidden" name="action" value="editskin">
   <input type="hidden" name="id" value="<?php echo $id; ?>">
   <input type="submit" value="Back to skin overview">
   </form>
  </td>
 </tr>
</table>
<?php
	cpShowFooter();
    }

    //
    // EditSkinVar()
    //
    // This will edit a skin variable.
    //
    function
    EditSkinVar() {
	// fetch the variables
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);
	$destvar = $_REQUEST["destvar"];

	// grab this variable
	$query = sprintf ("SELECT content,description FROM skinvars_%s WHERE name='%s'", $id,$destvar);
	list ($content, $desc) = db_fetch_results (db_query ($query));

	// build the page
	cpShowHeader ("Skin Maintenance", "Edit Skin Variable");
 ?><form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="hidden" name="action" value="doeditskinvar">
<input type="hidden" name="id" value="<?php echo $id; ?>">
<input type="hidden" name="destvar" value="<?php echo $destvar; ?>">
<table width="100%" class="tab5" cellspacing="1" cellpadding="4" border="0">
<tr class="tab2">
  <td width="20%"><b>Variable name</b></td>
  <td width="80%"><input type="text" name="the_varname" value="<?php echo htmlspecialchars ($destvar); ?>"></td>
</tr>
<tr class="tab2">
  <td><b>Description</b></td>
  <td><input type="text" name="the_desc" value="<?php echo htmlspecialchars ($desc); ?>"></td>
</tr>
<tr class="tab2">
  <td><b>Value</b></td>
  <td><input type="text" name="the_value" value="<?php echo htmlspecialchars ($content); ?>"></td>
</tr>
</table><p>
<table width="100%">
 <tr valign="top">
  <td width="50%" align="center"><input type="submit" value="Commit Changes"></form></td>
  <td width="50%" align="center"><form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post"><input type="hidden" name="action" value="deleteskinvar"><input type="hidden" name="id" value="<?php echo $id; ?>"><input type="hidden" name="destvar" value="<?php echo $destvar; ?>"><input type="submit" value="Delete skin variable"></form></td>
 </tr>
</table>
<?php
	cpShowFooter();
    }

    //
    // DoEditSkinVar()
    //
    // This will actually modify the skin variable.
    //
    function
    DoEditSkinVar() {
	// fetch the variables
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);
	$destvar = $_REQUEST["destvar"];
	$the_varname = $_REQUEST["the_varname"];
	$the_value = $_REQUEST["the_value"];
	$the_desc = $_REQUEST["the_desc"];

	// modify it
	$query = sprintf ("UPDATE skinvars_%s SET name='%s',content='%s',description='%s' WHERE name='%s'", $id, $the_varname, $the_value, $the_desc, $destvar);
	db_query ($query);

	// rebuild the stylesheet
	RebuildStyleSheet ($id);

	// it worked. inform the user
	cpShowHeader("Skin Maintenance", "Edit Skin Variable");
 ?>Thank you, the variable has successfully been updated.<p>
<form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="hidden" name="action" value="editskinvars">
<input type="hidden" name="id" value="<?php echo $id; ?>">
<input type="submit" value="Back to variable overview">
</form>
<?php
	cpShowFooter();
    }

    //
    // AddSkinVar()
    //
    // This will add the skin template.
    //
    function
    AddSkinVar() {
	// build the page
	cpShowHeader("Skin Maintenance", "Add Skin Variable");
 ?><form action="<?php echo $PHP_SELF; ?>" method="post">
<input type="hidden" name="action" value="doaddskinvar">
<input type="hidden" name="id" value="<?php echo preg_replace ("/\D/", "", $_REQUEST["id"]); ?>">
<table width="100%" class="tab5" cellspacing="1" cellpadding="4" border="0">
<tr class="tab2">
  <td width="20%"><b>Variable name</b></td>
  <td width="80%"><input type="text" name="the_varname"></td>
</tr>
<tr class="tab2">
  <td width="20%"><b>Description</b></td>
  <td width="80%"><input type="text" name="the_desc"></td>
</tr>
<tr class="tab2">
  <td><b>Value</b></td>
  <td><input type="text" name="the_value"></td>
</tr></table><p>
<center><input type="submit" value="Add skin variable"></center>
</form>
<?php
	cpShowFooter();
    }

    //
    // DoAddSkinVar()
    //
    // This will actually add a skin variable.
    //
    function
    DoAddSkinVar() {
	// fetch the variables
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);
	$the_varname = $_REQUEST["the_varname"];
	$the_value = $_REQUEST["the_value"];
	$the_desc = $_REQUEST["the_desc"];

	// build the query
	$query = sprintf ("INSERT INTO skinvars_%s VALUES ('%s','%s','%s')", $id, $the_varname, $the_value, $the_desc);
	db_query ($query);

	// rebuild the stylesheet
	RebuildStyleSheet ($id);

	// show the 'yay' page
	cpShowHeader("Skin Maintenance", "Add Skin Variable");
	print "Thank you, the variable has successfully been added.<p>";
 ?><form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="hidden" name="action" value="editskinvars">
<input type="hidden" name="id" value="<?php echo $id; ?>">
<input type="submit" value="Return to skin variable overview">
</form>
<?php

	cpShowFooter();
    }

    //
    // DoDeleteSkinTemplate()
    //
    // This will delete a skin template.
    //
    function
    DeleteSkinTemplate() {
	// build the query
	$query = sprintf ("DELETE FROM skin_%s WHERE name='%s'", preg_replace ("/\D/", "", $_REQUEST["id"]), $_REQUEST["template"]);
	db_query ($query);

	// this worked. inform the user
	cpShowHeader("Skin Maintenance", "Delete skin template");
 ?><form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<form action="<?php echo $PHP_SELF; ?>" method="post">
<input type="hidden" name="action" value="editskin">
<input type="hidden" name="id" value="<?php echo $id; ?>">
<input type="submit" value="Return to template overview">
</form>
<?php
	cpShowFooter();
    }

    //
    // DeleteSkinVar()
    //
    // This will delete a skin variable.
    //
    function
    DeleteSkinVar() {
	// fetch the values
	$id = preg_replace ("/\D/", "", $_REQUEST["id"]);
	$destvar = $_REQUEST["destvar"];

	// bye bye
	$query = sprintf ("DELETE FROM skinvars_%s WHERE name='%s'", $id, $destvar);
	db_query ($query);

	// rebuild the stylesheet
	RebuildStyleSheet ($id);

	// this worked. inform the user
	cpShowHeader("Skin Maintenance", "Edit Skin Variable");
 ?>Thank you, the variable has successfully been deleted.<p>
<form action="<?php echo $_SERVER["PHP_SELF"]; ?>" method="post">
<input type="hidden" name="action" value="editskinvars">
<input type="hidden" name="id" value="<?php echo $id; ?>">
<input type="submit" value="Return to skin variable overview">
</form>
<?php
	cpShowFooter();
    }

    // verify the rights
    cpVerifyAccess (CPOPTION_SKINS);

    // fetch the action
    $action = trim ($_REQUEST["action"]);

    // need to show the overview?
    if (($action == "") or ($action == "overview")) {
	// yes. do it
	Overview();
    } elseif ($action == "editskin") {
	// edit a skin
	EditSkin();
    } elseif ($action == "editskintemplate") {
	// edit a skin template
	EditSkinTemplate();
    } elseif ($action == "doeditskintemplate") {
	// actually edit a skin template
	DoEditSkinTemplate();
    } elseif ($action == "addskintemplate") {
	// add a skin template
	AddSkinTemplate();
    } elseif ($action == "doaddskintemplate") {
	// actually add a skin template
	DoAddSkinTemplate();
    } elseif ($action == "exportskin") {
	// export a skin
	ExportSkin();
    } elseif ($action == "importskin") {
	// import a skin
	ImportSkin();
    } elseif ($action == "doimportskin") {
	// actually import a skin
	DoImportSkin();
    } elseif ($action == "deleteskin") {
	// delete a skin
	DeleteSkin();
    } elseif ($action == "setskindefault") {
	// set a default skin
	SetSkinDefault();
    } elseif ($action == "editskinvars") {
	// edit the skin variables
        EditSkinVars();
    } elseif ($action == "editskinvar") {
	// edit a skin variable
	EditSkinVar();
    } elseif ($action == "doeditskinvar") {
	// actually edit a skin variable
	DoEditSkinVar();
    } elseif ($action == "addskinvar") {
	// add a skin variable
	AddSkinVar();
    } elseif ($action == "doaddskinvar") {
	// actually add the skin variable
	DoAddSkinVar();
    } elseif ($action == "deleteskintemplate") {
	// delete a skin template
	DeleteSkinTemplate();
    } elseif ($action == "deleteskinvar") {
	// delete a skin variable
	DeleteSkinVar();
    }
 ?>
